### ISSUE TITLE
Compile error Arduino, Details.h, Max(void), Min(Void)

### ISSUE THREAD

**Issue by coolpluggy** [Pharap/FixedPointsArduino#13]
Get the following error compiling the example:

Arduino: 1.8.5 (Mac OS X), Board:"Arduino Due (Programming Port)"

In file included from /Users/username/Documents/Arduino/libraries/FixedPoints/src/FixedPoints/FixedPoints.h:15:0,
                 from /Users/username/Documents/Arduino/libraries/FixedPoints/src/FixedPoints.h:15,
                 from /Users/username/Documents/Arduino/libraries/FixedPoints/examples/FixedPointCalculations/FixedPointCalculations.ino:1:
/Users/username/Documents/Arduino/libraries/FixedPoints/src/FixedPoints/Details.h:57:25: error: macro "Max" requires 2 arguments, but only 1 given
  constexpr auto Max(void) noexcept -> decltype((Left > Right) ? Left : Right)

                         ^
/Users/username/Documents/Arduino/libraries/FixedPoints/src/FixedPoints/Details.h:69:25: error: macro "Min" requires 2 arguments, but only 1 given
  constexpr auto Min(void) noexcept -> decltype((Left < Right) ? Left : Right)

                         ^

**Comment by Pharap** [comment]
FixedPoints hasn't been tested with SAM boards before.

I've had a quick test and it's possible to get it to compile for a Due if you don't need the `Min` and `Max` macros or the random functions.

If you put the following at the top of your code then it should compile for now:
```
#undef Min
#undef Max
#define FIXED_POINTS_NO_RANDOM
#include <FixedPoints.h>
#include <FixedPointsCommon.h>
```

---

I'll look into changing the `Min` and `Max` macros and temporarily disabling the random functions for Due until I have chance to create a more robust solution to the random functions or come up with an alternative (like splitting them into a separate header).
I don't currently have the time to do so but I'll try to get it done as soon as possible.

If you do need to use `Min` and `Max` then you can do a find-and-replace in Details.h.
(If you intend to publish your work, you'd need to leave a comment at the top of the file to say that you've changed them.)

**Comment by Pharap** [comment]
I've introduced a potential solution into a test branch:
https://github.com/Pharap/FixedPointsArduino/commits/Due-support

It compiles but I don't have a Due to test it on so I'll need you to test the example to make sure it runs correctly.

---

The expected output is as thus:
```
The size of UQ8x8 on your system is:
2

Displaying a as float:
1.50

Displaying the integer part of a
1

Displaying floorFixed(a):
1.00

Displaying ceilFixed(a):
2.00

Displaying roundFixed(a):
2.00

Displaying truncFixed(a):
1.00

Displaying b as float:
5.25

Displaying the integer part of b
5

Displaying floorFixed(b):
5.00

Displaying ceilFixed(b):
6.00

Displaying roundFixed(b):
5.00

Displaying truncFixed(b):
5.00

Displaying a + b as float:
6.75

Displaying a - b as float:
(Note the underflow due lack of sign bit)
252.25

Displaying b - a as float:
3.75

Displaying a * b as float:
7.88

Displaying a / b as float:
0.29

The size of SQ7x8 on your system is:
2

Displaying a as float:
1.50

Displaying the integer part of a
1

Displaying floorFixed(a):
1.00

Displaying ceilFixed(a):
2.00

Displaying roundFixed(a):
2.00

Displaying truncFixed(a):
1.00

Displaying b as float:
5.25

Displaying the integer part of b
5

Displaying floorFixed(b):
5.00

Displaying ceilFixed(b):
6.00

Displaying roundFixed(b):
5.00

Displaying truncFixed(b):
5.00

Displaying a + b as float:
6.75

Displaying a - b as float:
(Note this is correct due to sign bit)
-3.75

Displaying b - a as float:
3.75

Displaying a * b as float:
7.88

Displaying a / b as float:
0.29


```

**Comment by coolpluggy** [comment]
Now it compiles and runs on a Due!

There is slight difference in the results for the multiplication, both for UQ8.8 and SQ7x8.
```
Displaying a * b as float:
7.87
```
in stead of 7.88

And you need to add
  Serial.begin(9600);
to the example into in the setup function to see the results in the serial monitor.

**Comment by Pharap** [comment]
I'm used to using systems where `Serial.begin` isn't needed.
If it'd definitely needed for other boards then I'll add it.

The slight difference is probably just a minor rounding error due to the implementation of the print function or perhaps the precision of the types on the Due, which is to be expected.
If that's the only difference in output then I think it's safe to call it 'compatible'.

**Comment by Pharap** [comment]
Due support has been added by PR #16.

**Comment by Pharap** [comment]
In the end I roped in some outside help again.

Fix tested by @adekto.
