### ISSUE TITLE
Error in library.json

### ISSUE THREAD

**Issue by MLXXXp** [Pharap/FixedPointsArduino#2]
https://github.com/Pharap/FixedPointsArduino/blob/393acd2f49f66bfbb2a1b70def0258b5e3ce0b5d/library.json#L15

There shouldn't be a comma after _"tests"_

**Comment by MLXXXp** [comment]
Since you don't have a file or directory named _tests_ in the repository, as it stands you don't need an _exclude_ keyword.

**Comment by Pharap** [comment]
To clarify, the 'library.json' file is not needed for the Arduino IDE and is in fact only required for PlatformIO support?

**Comment by MLXXXp** [comment]
Correct. Only _library.properties_ is needed for the Arduino IDE Library Manager.

**Comment by Pharap** [comment]
PlatformIO support might be added at some point in the future when there is time to sit down and properly consider it, but until that point `library.json` is not required.
As such I am removing `library.json` until PlatformIO support is up for consideration as it is not serving any other purpose.

**Comment by MLXXXp** [comment]
_library.json_ is all you need for full PlatformIO support. There's nothing else to "sit down and properly consider".

You just have to remove the _exclude_ object, since the comma after _"tests"_ is a json error and the entire _exclude_ object is unnecessary anyway.

You then only have to maintain it by keeping the _version_ field in sync whenever you change it in _library.properties_

**Comment by Pharap** [comment]
I have yet to consider whether I _want_ to support it, which I will do when I have the time.
